using System.Globalization;
using System.Text;

var repositoryRoot = FindRepositoryRoot(Environment.CurrentDirectory);
var outputPath = Path.Combine(
    repositoryRoot,
    "RagEdu.Tests",
    "Generated",
    "QuizAnswerRegressionScenarios.g.cs");

var technicalPhrases = new[]
{
    "ASP.NET Core",
    "Entity Framework Core",
    "Dependency Injection",
    "Model View Controller",
    "Razor Pages",
    "Minimal API",
    "Web API",
    "Object Relational Mapping",
    "Language Integrated Query",
    "Structured Query Language",
    "JavaScript Object Notation",
    "Representational State Transfer",
    "Domain Driven Design",
    "Clean Architecture",
    "Repository Pattern",
    "Unit of Work",
    "Command Query Responsibility Segregation",
    "Model Binding",
    "Data Annotation",
    "Authentication Middleware",
    "Authorization Policy",
    "Health Check",
    "Rate Limiting",
    "Global Exception Handler",
    "Audit Log",
    "Question Bank",
    "Quiz Version",
    "Learning Analytics",
    "Flashcard",
    "Speed Challenge",
    "Thẻ ghi nhớ",
    "Ngân hàng câu hỏi",
    "Bài kiểm tra",
    "Lập trình hướng đối tượng",
    "Cơ sở dữ liệu",
    "Kiểm thử đơn vị",
    "Kiểm thử tích hợp",
    "Xử lý ngoại lệ",
    "Phân quyền người dùng",
    "Nhật ký thao tác",
    "Khôi phục phiên bản",
    "Phân tích độ khó",
    "Tỷ lệ chọn đáp án",
    "Giảng viên",
    "Sinh viên",
    "Quản trị viên",
    "Môn học",
    "Tài liệu học tập",
    "Câu hỏi trắc nghiệm",
    "Đáp án chính xác",
    "Trung bình",
    "Dễ",
    "Khó",
    "Đúng",
    "Bất đồng bộ",
    "Đa nền tảng",
    "Bộ nhớ đệm",
    "Chuỗi kết nối",
    "Giao diện người dùng",
    "Trải nghiệm người dùng"
};

var scenarios = new List<Scenario>();
var sequence = 1;
foreach (var phrase in technicalPhrases)
{
    var equivalentVariants = new[]
    {
        phrase,
        phrase.ToLowerInvariant(),
        phrase.ToUpperInvariant(),
        $"   {phrase}   ",
        phrase.Replace(" ", "   ", StringComparison.Ordinal),
        phrase.Replace(" ", "-", StringComparison.Ordinal),
        phrase.Replace(" ", "/", StringComparison.Ordinal),
        RemoveVietnameseDiacritics(phrase),
        RemoveVietnameseDiacritics(phrase).ToUpperInvariant(),
        $"({phrase})",
        phrase.Replace(" ", "\t\n", StringComparison.Ordinal),
        phrase.Replace(" ", "___", StringComparison.Ordinal)
    };

    foreach (var selectedAnswer in equivalentVariants)
    {
        scenarios.Add(new Scenario(
            $"answer-{sequence++:0000}",
            phrase,
            selectedAnswer,
            ExpectedCorrect: true));
    }

    var differentVariants = new[]
    {
        $"{phrase} khác",
        $"không {phrase}",
        $"{phrase} phiên bản sai"
    };
    foreach (var selectedAnswer in differentVariants)
    {
        scenarios.Add(new Scenario(
            $"answer-{sequence++:0000}",
            phrase,
            selectedAnswer,
            ExpectedCorrect: false));
    }
}

if (scenarios.Count != 900)
{
    throw new InvalidOperationException(
        $"The regression catalog must contain exactly 900 scenarios, but generated {scenarios.Count}.");
}

var source = new StringBuilder();
source.AppendLine("// <auto-generated />");
source.AppendLine("// Generated by tools/QuizRegressionMatrixGenerator.");
source.AppendLine("// Every row is executed through LearningService.SubmitQuizAsync.");
source.AppendLine();
source.AppendLine("namespace RagEdu.Tests.Generated;");
source.AppendLine();
source.AppendLine("public static class QuizAnswerRegressionScenarios");
source.AppendLine("{");
source.AppendLine("    public static IEnumerable<object[]> All");
source.AppendLine("    {");
source.AppendLine("        get");
source.AppendLine("        {");
foreach (var scenario in scenarios)
{
    source.AppendLine("            yield return");
    source.AppendLine("            [");
    source.AppendLine("                new AnswerNormalizationScenario");
    source.AppendLine("                {");
    source.AppendLine($"                    Id = {Literal(scenario.Id)},");
    source.AppendLine($"                    CorrectAnswer = {Literal(scenario.CorrectAnswer)},");
    source.AppendLine($"                    SelectedAnswer = {Literal(scenario.SelectedAnswer)},");
    source.AppendLine($"                    ExpectedCorrect = {scenario.ExpectedCorrect.ToString().ToLowerInvariant()}");
    source.AppendLine("                }");
    source.AppendLine("            ];");
    source.AppendLine();
}
source.AppendLine("        }");
source.AppendLine("    }");
source.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, source.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Generated {scenarios.Count} executable scenarios at {outputPath}.");

static string FindRepositoryRoot(string startPath)
{
    var directory = new DirectoryInfo(startPath);
    while (directory is not null)
    {
        if (File.Exists(Path.Combine(directory.FullName, "Assignmet1.sln")))
            return directory.FullName;
        directory = directory.Parent;
    }

    throw new DirectoryNotFoundException(
        $"Could not find Assignmet1.sln from '{startPath}'.");
}

static string RemoveVietnameseDiacritics(string value)
{
    var normalized = value.Normalize(NormalizationForm.FormD);
    var builder = new StringBuilder(normalized.Length);
    foreach (var character in normalized)
    {
        if (CharUnicodeInfo.GetUnicodeCategory(character) == UnicodeCategory.NonSpacingMark)
            continue;
        builder.Append(character switch
        {
            'Đ' => 'D',
            'đ' => 'd',
            _ => character
        });
    }
    return builder.ToString().Normalize(NormalizationForm.FormC);
}

static string Literal(string value)
{
    return "\""
        + value
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal)
        + "\"";
}

internal sealed record Scenario(
    string Id,
    string CorrectAnswer,
    string SelectedAnswer,
    bool ExpectedCorrect);
